name: Docker Image CI

on:
  push:
    branches: ["main"]

jobs:

  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    
    - name: Checkout
      uses: actions/checkout@v4

    - name: Docker login to GHCR
      env:
        DOCKER_USER: ${{ github.actor }}
        DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

      run: |
        echo "Iniciando login"
        echo "$DOCKER_PASSWORD" | docker login ghcr.io -u $DOCKER_USER --password-stdin
        echo "Fin del login"
    
    - name: Build image
      run: docker build -t ghcr.io/${{ github.repository }} .

    - name: Push image
      run: docker push ghcr.io/${{ github.repository }}:0.0.1
    #- name: Build Docker Image
      #run: |
        #docker build --tag jorgam98/transitions-page:0.0.6 .

    #- name: Push Docker Image
      #run: |
        #docker push jorgam98/transitions-page:0.0.6
    
    #- name: Build the Docker image
    #  run: docker build . --file DockerFile --tag my-image-name:$(date +%s)
